### ISSUE TITLE
Can KGySoft.Drawing be a replacement for SkiaSharp? 

### ISSUE THREAD

**Issue by sgf** [koszeggy/KGySoft.Drawing#16]
The SkiaSharp dll file is too large, close to 10mb.
I'm looking for a 2d graphics library developed in pure C#

**Comment by koszeggy** [comment]
It depends on what do you want to use it for. As it still lacks some areas other libraries support, today it's mainly a complementary library for the well-known libraries to support some specialized tasks.

For example, it lacks shape drawing features so far (though I started to work on that on an unpublished branch), and apart from a GIF encoder it does not contain encoders and decoders for popular file formats. The basic idea is that you can load image files with your favorite image library, which can be reinterpreted as `IReadWriteBitmapData` instances to manipulate them by my library.

But even if there will be shape drawing support along with more encoders and decoders, I don't expect to implement some other important features such as some platform independent font rendering anytime soon...

**Comment by sgf** [comment]
> It depends on what do you want to use it for. As it still lacks some areas other libraries support, today it's mainly a complementary library for the well-known libraries to support some specialized tasks.
> 
> For example, it lacks shape drawing features so far (though I started to work on that on an unpublished branch), and apart from a GIF encoder it does not contain encoders and decoders for popular file formats. The basic idea is that you can load image files with your favorite image library, which can be reinterpreted as `IReadWriteBitmapData` instances to manipulate them by my library.
> 
> But even if there will be shape drawing support along with more encoders and decoders, I don't expect to implement some other important features such as some platform independent font rendering anytime soon...

Encoders and decoders are not important for a graphics library. They are just peripheral facilities of the graphics library.
The important thing should be the drawing of primitives, shapes, images, and some operations.And finally they are rasterized and rendered.

However, your answer has pointed out some missing parts. Thank you very much for your answer.

**Comment by koszeggy** [comment]
Just noting that [shape drawing](https://github.com/koszeggy/KGySoft.Drawing/blob/master/README.md#shape-drawing) is now available in the [latest release](https://github.com/koszeggy/KGySoft.Drawing/releases/tag/v9.0.0).

It still could be improved (e.g. there is no hatch brush or dashed pens yet) but it already offers some special features that the regular libraries don't have, e.g. async drawing, using more cores, supporting bitmaps with an indexed pixel format or using optimized special handling for some primitive shapes when possible.
