### ISSUE TITLE
Ditherer parameter not optional?

### ISSUE THREAD

**Issue by wimpie3** [koszeggy/KGySoft.Drawing#6]
I'm using your library to dither an image in VB.net. That works fine as long as the second parameter is passed with the Dither function.

This works:
bmp.Dither(quantizer, ditherer)

But when I don't want to dither, this doesn't seem to work:
bmp.Dither(quantizer, Nothing)

I get anArgumentNullException error. According to your documentation the second parameter is optional.

**Comment by wimpie3** [comment]
OK, I think I got it, you actually need to use bmp.Quantize(quantizer) if you want to leave out the ditherer parameter... that wasn"t entirely clear to me.

**Comment by koszeggy** [comment]
> According to your documentation the second parameter is optional.

Quantizer and ditherer parameters are optional in most cases (cloning, converting pixel format, drawing into another bitmap data, etc.) but not for the [`Dither`](http://docs.kgysoft.net/drawing/?topic=html/M_KGySoft_Drawing_BitmapExtensions_Dither.htm) and [`Quantize`](http://docs.kgysoft.net/drawing/?topic=html/M_KGySoft_Drawing_BitmapExtensions_Quantize.htm) methods. I'm glad you found the solution in the end.

Btw, I've just turned on C# 8.0 nullable references for the project, so in the next release it will be more obvious whether a parameter allows null.
