### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by davidei1955** [koszeggy/KGySoft.Drawing#9]
KGySoft.Drawing is REALLY GREAT! I wish I'd know about it years ago. It has already solved several issues I've been working on for weeks. The code is really clean and well thought out. 

I don't see any support for .webp images, though. **Am I missing something? Is webp support planned as a future enhancement?** I've been using  WebP-wrapper from [JosePineiro](https://github.com/JosePineiro/WebP-wrapper), but it requires an unmanaged dll and doesn't support animated webp images. This is my only imaging issue that KGySoft.Drawing doesn't seem to solve.

Also, I try to support open source projects when I find them useful. I'm retired and on a fixed income, but I would donate a few dollars to your project if you had a way to accept PayPal donations on your website. Thanks again for your really useful code.

**Comment by koszeggy** [comment]
Thank you for you kind words.

> I don't see any support for .webp images

WebP support (along with APNG) is at the very bottom of my todo list. Most of the supported formats rely on GDI+ capabilities, which I extended by some custom solutions where there were some room for improvements (eg. saving icons, WMF/EMF formats, or animated GIFs).

And considering that non-Windows support of `System.Drawing.Common` is being [banned](https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only) starting with .NET 6 (and will be completely [removed](https://github.com/dotnet/designs/blob/main/accepted/2021/system-drawing-win-only/system-drawing-win-only.md) in .NET 7) I plan to extract some `KGySoft.Drawing.Common` from this library that contains the completely GDI-independent parts. To support common image formats in that independent library I will have to (re)implement all of the usual encoders and decoders. But then I could add further formats as well, including WebP.

> I try to support open source projects when I find them useful

I didn't set up accepting donations so far but you are not the first one who asks about it. I just didn't feel confident enough but it seems maybe the time has come. :)

I wish you good health and a happy new year!

**Comment by davidei1955** [comment]
Thank you and happy new year!

**Comment by koszeggy** [comment]
Well, better late than never but now as the number of my followers reached a certain amount I configured donations. If you are still interested, you can now use the Sponsor button at the top of the page.

Anyhow, I wish all the best and I'm glad you contacted me.
